import { writeFileSync, mkdirSync } from 'fs';
const D = 'shared/scripts/closebot/personas/montgomery';
mkdirSync(D, { recursive: true });
const P = {
  adult_fundamentals: { om: "Hi, I want to try a jiu-jitsu class", b: "You are {{firstName}} {{lastName}}, a 28-year-old adult (DOB: 1997-05-09), new to BJJ, booking a free trial for yourself. No format preference - if asked say you're a beginner / open. Give info when asked: {{firstName}} {{lastName}}, email {{email}}, phone {{phone}}, DOB 1997-05-09. Accept the first slot offered. Expect to be booked into Adult Fundamentals BJJ. When the bot confirms the booking, reply with [END]." },
  adult_inquisitive: { om: "do you have a leg locks or ADCC no-gi class I can start with?", b: "You are {{firstName}} {{lastName}}, a 30-year-old adult (DOB: 1995-03-14) who asks about starting in the Leg Locks or ADCC No-Gi specialty class. Those are advanced specialty classes, not the beginner trial. EXPECT the bot to acknowledge they exist but steer you to the free beginner/fundamentals trial instead. Give your info when asked: {{firstName}} {{lastName}}, email {{email}}, phone {{phone}}, DOB 1995-03-14. Accept the fundamentals trial slot. When booked or politely closed, reply with [END]." },
  kid_3_6: { om: "I want to sign my 5 year old up for jiu-jitsu", b: "You are {{firstName}} {{lastName}}, a parent (your DOB: 1988-09-02) enrolling your son Eli, age 5 (DOB: 2020-07-15). When asked who it is for, say your 5 year old son. Cooperatively give your contact: {{firstName}} {{lastName}}, email {{email}}, phone {{phone}}, your DOB 1988-09-02. Child: Eli, DOB 2020-07-15. Expect Eli booked into Kids Brazilian Jiu-Jitsu (3-6). Accept the first slot. When the bot confirms the booking, reply with [END]." },
  kid_7_13: { om: "my daughter is 10 and wants to start bjj", b: "You are {{firstName}} {{lastName}}, a parent (your DOB: 1985-11-20) enrolling your daughter Nora, age 10 (DOB: 2015-04-08). When asked who it is for, say your 10 year old daughter. Cooperatively give your contact: {{firstName}} {{lastName}}, email {{email}}, phone {{phone}}, your DOB 1985-11-20. Child: Nora, DOB 2015-04-08. Expect Nora booked into Kids Brazilian Jiu-Jitsu (7-13). Accept the first slot. When the bot confirms the booking, reply with [END]." },
  teen_14_17_nocal: { om: "my son is 15 and wants to train bjj", b: "You are {{firstName}} {{lastName}}, a parent (your DOB: 1981-06-12) enrolling your son Kai, age 15 (DOB: 2010-10-30). When asked who it is for, say your 15 year old son. Cooperatively give your contact: {{firstName}} {{lastName}}, email {{email}}, phone {{phone}}, your DOB 1981-06-12. Child: Kai, DOB 2010-10-30. Montgomery has NO online class for ages 14-17 (kids end at 13, adults are 18+). EXPECT the bot to NOT book any class and instead say the team will follow up to get Kai set up. Do not push to be booked. When the bot says the team will reach out / closes, reply with [END]." },
  adult_and_kid: { om: "I want to train and also get my kid into bjj", b: "You are {{firstName}} {{lastName}}, a 36-year-old adult (DOB: 1989-02-17) enrolling BOTH yourself and your daughter Lily, age 8 (DOB: 2017-08-05). When asked who it is for, say both you and your 8 year old daughter. Give: {{firstName}} {{lastName}}, email {{email}}, phone {{phone}}, your DOB 1989-02-17. Child: Lily, DOB 2017-08-05. Expect yourself booked into Adult Fundamentals BJJ and Lily into Kids Brazilian Jiu-Jitsu (7-13). Accept the first slots. When both bookings are confirmed, reply with [END]." },
  minor_self_booking: { om: "hey i want to start bjj, how do i sign up", b: "You are {{firstName}} {{lastName}}, a 16-year-old (DOB: 2009-01-22) trying to sign YOURSELF up with NO parent involved. Say it is just for you. Refuse / deflect if asked for a parent or guardian ('I'm handling this myself'). Never provide a guardian. Expect the bot to NOT book you and instead say the team will follow up to involve a parent/guardian. When the bot closes or says the team will reach out, reply with [END]." },
  under3_redirect: { om: "can I enroll my 2 year old in jiu-jitsu?", b: "You are {{firstName}} {{lastName}}, a parent (your DOB: 1992-12-01) asking about your 2-year-old child Theo (DOB: 2023-10-10). When asked who it is for, say your 2 year old. Give your contact if asked. Montgomery's youngest program is ages 3+, so a 2-year-old is too young. EXPECT the bot to NOT book anything and refer you to call the academy at (609) 355-7500. Do not push. When the bot redirects you to the phone number or closes, reply with [END]." },
  pricing_deflect: { om: "how much does a membership cost per month?", b: "You are {{firstName}} {{lastName}}, a 33-year-old adult (DOB: 1992-04-27) who pushes hard for a price. Ask the monthly cost again at least twice if the bot deflects. Eventually accept a free trial if the bot stays firm and never gives a figure. Give {{firstName}} {{lastName}}, email {{email}}, phone {{phone}}, DOB 1992-04-27 when asked. When booked or politely closed, reply with [END]." },
  nonbookable_program: { om: "can I book Open Mat as my first session?", b: "You are {{firstName}} {{lastName}}, an adult (DOB: 1990-08-19) asking to book Open Mat or the Kids Competition Class as your first/trial session. These are not intro/trial sessions. EXPECT the bot to acknowledge they exist but NOT book them, and instead offer the free beginner/fundamentals trial. Give your info if asked. When redirected to the trial or closed, reply with [END]." },
  hostile_aggression: { om: "stop messaging me. remove me now.", b: "You are {{firstName}} {{lastName}}, hostile and want off the list. Demand removal. Give no personal info. When the bot acknowledges and stops / removes you, reply with [END]." }
};
let n = 0;
for (const [k, v] of Object.entries(P)) {
  writeFileSync(`${D}/${k}.json`, JSON.stringify({ persona_id: `montgomery_${k}`, opening_message: v.om, brief: v.b }, null, 2) + '\n');
  n++; console.log('  wrote', k, ':: montgomery_' + k);
}
console.log(`Generated ${n} Montgomery personas (persona_id normalized)`);
